name = "minecraft-vanilla-pack-server"
mc_version = "1.21.5"

[jar]
type = "fabric"
loader = "0.16.10"
installer = "latest"

[variables]
SERVER_PORT = "25565"
MOTD = "There §2§oWILL§r be bugs!!"

[launcher]
eula_args = true
nogui = true
jvm_args = "--add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:SurvivorRatio=32 -XX:G1HeapWastePercent=5 -XX:MaxTenuringThreshold=1 -XX:+PerfDisableSharedMem -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:+UseNUMA -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:NmethodSweepActivity=1 -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:AllocatePrefetchStyle=3 -XX:+AlwaysActAsServerClassMachine -XX:+UseTransparentHugePages -XX:LargePageSizeInBytes=2M -XX:+UseLargePages -XX:+EagerJVMCI -XX:+UseStringDeduplication -XX:+UseAES -XX:+UseAESIntrinsics -XX:+UseFMA -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseThreadPriorities -XX:+OmitStackTraceInFastThrow -XX:+RewriteBytecodes -XX:+RewriteFrequentPairs -XX:+UseFPUForSpilling -XX:+UseVectorCmov -XX:+UseXMMForArrayCopy -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+AlignVector -XX:+OptimizeFill -XX:+EnableVectorSupport -XX:+UseCharacterCompareIntrinsics -XX:+UseCopySignIntrinsic -XX:+UseVectorStubs -XX:+UseFastJNIAccessors -XX:+UseInlineCaches -XX:+SegmentedCodeCache -Djdk.nio.maxCachedBufferSize=262144 -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.DetectInvertedLoopsAsCounted=true  -Dgraal.LoopInversion=true -Dgraal.VectorizeHashes=true -Dgraal.EnterprisePartialUnroll=true -Dgraal.VectorizeSIMD=true -Dgraal.StripMineNonCountedLoops=true  -Dgraal.SpeculativeGuardMovement=true -Dgraal.TuneInlinerExploration=1 -Dgraal.LoopRotation=true -Dgraal.CompilerConfiguration=enterprise"
memory = "8G"

[markdown]
files = ["README.md"]
auto_update = true

[options]
success_line = ""
stop_command = ""

[[worlds.world.datapacks]]
type = "modrinth"
id = "wabi-sabi-structures"
version = "8ZQeQ2MJ"

[[worlds.world.datapacks]]
type = "modrinth"
id = "clifftree"
version = "QXK2sYnv"

[[worlds.world.datapacks]]
type = "modrinth"
id = "sleep"
version = "pyubmJ41"

[[mods]]
type = "modrinth"
id = "badoptimizations"
version = "EPTfY6pQ"

[[mods]]
type = "modrinth"
id = "5ZwdcRci"
version = "DjnwJdjY"

[[mods]]
type = "modrinth"
id = "c2me-fabric"
version = "Wh5CxZTp"

[[mods]]
type = "modrinth"
id = "9s6osm5g"
version = "qA00xo1O"

[[mods]]
type = "modrinth"
id = "LQ3K71Q1"
version = "plAPgk28"

[[mods]]
type = "modrinth"
id = "NNAgCjsB"
version = "29GV7fju"

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "rYSz5dRU"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "CtMpt7Jr"

[[mods]]
type = "modrinth"
id = "fQEb0iXm"
version = "neW85eWt"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "VWYoZjBF"

[[mods]]
type = "modrinth"
id = "4WWQxlQP"
version = "VK0kd4wj"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "DA250htH"

[[mods]]
type = "modrinth"
id = "vSEH1ERy"
version = "HV6EY0h3"

[[mods]]
type = "modrinth"
id = "wnEe9KBa"
version = "EKg6v67t"

[[mods]]
type = "modrinth"
id = "1eAoo2KR"
version = "5yBEzonb"

[[mods]]
type = "modrinth"
id = "WwbubTsV"
version = "KMOzdYko"

[[mods]]
type = "modrinth"
id = "spark"
version = "NURCAL12"

[[mods]]
type = "modrinth"
id = "distanthorizons"
version = "Mt9bDAs6"

[[mods]]
type = "modrinth"
id = "jline4mcdsrv"
version = "QYNpu9bc"

[[mods]]
type = "modrinth"
id = "debugify"
version = "rfvoZgM1"
